# Generated by Django 4.0.2 on 2022-04-25 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('parser_name', models.TextField(null=True)),
                ('parser_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.TextField(default='section 1', null=True)),
                ('xpath_url', models.TextField()),
                ('xpath_method', models.CharField(choices=[('article_text', 'process_article_text'), ('singular_item', 'process_singular_item'), ('date_item', 'process_date_item'), ('plural_texts', 'process_plural_texts'), ('external_links', 'process_external_links'), ('array_item', 'process_array_item'), ('text_array_from_string', 'process_text_array_from_string')], default='article_text', max_length=22)),
                ('parser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.parser')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.TextField()),
                ('parser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.parser')),
            ],
        ),
    ]
