# Generated by Django 4.0.2 on 2022-05-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_rename_parser_id_parser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpath',
            name='xpath_additions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='xpath',
            name='xpath_class',
            field=models.TextField(default='section'),
        ),
    ]
