# Generated by Django 4.0.2 on 2022-05-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_xpath_xpath_additions_xpath_xpath_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpath',
            name='manual',
            field=models.BooleanField(default=True),
        ),
    ]
