# Generated by Django 4.0.2 on 2022-05-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_xpath_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpath',
            name='xpath_additions',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='xpath',
            name='xpath_class',
            field=models.TextField(default='section', null=True),
        ),
    ]
