# Generated by Django 4.0.2 on 2022-05-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_remove_xpath_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpath',
            name='xpath_url',
            field=models.TextField(default='', null=True),
        ),
    ]
