# Generated by Django 4.0.2 on 2022-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_alter_xpath_xpath_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpath',
            name='xpath_class',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='xpath',
            name='xpath_method',
            field=models.CharField(choices=[('article_text', 'process_article_text'), ('singular_item', 'process_singular_item'), ('external_links', 'process_external_links'), ('array_item', 'process_array_item')], default='article_text', max_length=22),
        ),
    ]
