# Generated by Django 4.0.2 on 2022-05-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_alter_url_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_name',
            field=models.TextField(help_text='<span class="tooltip">?<span class="tooltiptext">Enter link to website</span></span>'),
        ),
    ]
