# Generated by Django 4.0.2 on 2022-05-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_alter_url_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpath',
            name='section_name',
            field=models.TextField(default='section 1', help_text='<span class="tooltip">?<span class="tooltiptext">Enter section name</span></span>', null=True),
        ),
        migrations.AlterField(
            model_name='xpath',
            name='xpath_url',
            field=models.TextField(default='', help_text='<span class="tooltip">?<span class="tooltiptext">Enter XPath formula</span></span>', null=True),
        ),
    ]
