# Generated by Django 4.0.2 on 2022-05-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_alter_xpath_section_name_alter_xpath_xpath_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='parser_name',
            field=models.TextField(help_text='<span class="tooltip">?<span class="tooltiptext">Enter parser name</span></span>', null=True),
        ),
        migrations.AlterField(
            model_name='xpath',
            name='xpath_additions',
            field=models.TextField(default='', help_text='<span class="tooltip">?<span class="tooltiptext">Enter html path from class to element</span></span>', null=True),
        ),
        migrations.AlterField(
            model_name='xpath',
            name='xpath_class',
            field=models.TextField(default='', help_text='<span class="tooltip">?<span class="tooltiptext">Enter html class</span></span>', null=True),
        ),
        migrations.AlterField(
            model_name='xpath',
            name='xpath_method',
            field=models.CharField(choices=[('article_text', 'process_article_text'), ('singular_item', 'process_singular_item'), ('external_links', 'process_external_links'), ('array_item', 'process_array_item')], default='article_text', help_text='<span class="tooltip">?<span class="tooltiptext">Select XPath processing method</span></span>', max_length=22),
        ),
    ]
